### ISSUE TITLE
Option to get resolution of file without transcoding

### ISSUE THREAD

**Issue by agxp** [xfrr/goffmpeg#11]
First, thanks for this library as it's incredibly useful and it was very hard to find simple libraries to wrap around ffmpeg for easy video encoding.

One of the features I need is to be able to know the resolution of a file and make decisions based on that, but I couldn't get it working. (Maybe just using ffprobe)

Is this something you could add? I'm not clear on how to implement it without using Transcoder.Initialize (but that gives me a fault if I don't finish the encode).

Thanks

**Comment by xfrr** [comment]
Hi, first, thanks for contributing.
When you initialize the "transcoding" passing the input file and the outputfile, you can access directly to the Mediafile instance and properties.
```go
package main

import (
    "goffmpeg/transcoder"
	"fmt"
)

var inputPath = "/data/testmov"
var outputPath = "/data/testmp4.mp4"

func main() {
    trans := new(transcoder.Transcoder)

    err := trans.Initialize( inputPath, outputPath )
    if err != nil {
    	panic(err)
	}

	fmt.Println(trans.MediaFile().Metadata().Streams[0].Width)
	fmt.Println(trans.MediaFile().Metadata().Streams[0].Height)

        ...
}
```
You can get the resolution obtaining "width" and "height" from video stream.
Note: you will have to know which one is the video stream first.
