### ISSUE TITLE
make audio bitrate an integer similar to video bitrate

### ISSUE THREAD

**Issue by muhammadharis** [xfrr/goffmpeg#37]
Was wondering if it would be possible to make audio bitrate an integer, makes more sense and follows the convention of video bitrate being an integer.

In theory, it would be a good idea if they were both uint32, considering bitrates don't dip below 0.

**Comment by xfrr** [comment]
Considering ffmpeg accepts string as audio bitrate, I think it's a good idea keep it that way...

**Comment by muhammadharis** [comment]
That's fair, the reason i brought this up is because the current implementation has video bitrate as an int as well. Perhaps we should change that to string as well to keep it consistent?
