### ISSUE TITLE
 (*Mediafile).SetMovFlags redeclared in this block

### ISSUE THREAD

**Issue by shahinesi** [xfrr/goffmpeg#50]
GOROOT=D:\Go #gosetup
GOPATH=C:\Users\shahi\go #gosetup
D:\Go\bin\go.exe get -t -v github.com/xfrr/goffmpeg/transcoder/... #gosetup
github.com/xfrr/goffmpeg (download)
github.com/xfrr/goffmpeg/models
# github.com/xfrr/goffmpeg/models
C:\Users\shahi\go\src\github.com\xfrr\goffmpeg\models\media.go:352:21: (*Mediafile).SetMovFlags redeclared in this block
	previous declaration at C:\Users\shahi\go\src\github.com\xfrr\goffmpeg\models\media.go:260:6
C:\Users\shahi\go\src\github.com\xfrr\goffmpeg\models\media.go:1166:21: (*Mediafile).ObtainMovFlags redeclared in this block
	previous declaration at C:\Users\shahi\go\src\github.com\xfrr\goffmpeg\models\media.go:776:6

help me

**Comment by vivienbcr** [comment]
Yeasterday merges seem break app.. You can manualy use previous master version.
