### ISSUE TITLE
(*Mediafile).ObtainMovFlags redeclared in this block

### ISSUE THREAD

**Issue by graux** [xfrr/goffmpeg#51]
You have duplicated the method ObtainMovFlags.

Fran, parece que te ha ocurrido lo mismo con SetMovFlags.
Creo que somos unos cuantos que estamos usando tu proyecto, y este tipo de cambios nos impiden compilar.
Te recomendaría que hicieras los siguientes cambios en el proyecto:
- Desarrolla tus cambios en otra rama, no master.
- Más pruebas unitarias
- Si las pruebas unitarias no pasan, no hagas merge a master.
- Intenta implementar el proyecto con modules y versiona los cambios.

Gracias

**Comment by xfrr** [comment]
Gracias por el fix, parece que tuve problemas al mergear una PR y no me di cuenta, perdonad por el desastre.

**Comment by graux** [comment]
Gracias a ti!
Un saludo y suerte con el aislamiento ;)

**Comment by xfrr** [comment]
Igualmente, espero que todo vaya bien, un saludo :)
