### ISSUE TITLE
find ffprope error at windows

### ISSUE THREAD

**Issue by sunriquelme** [xfrr/goffmpeg#58]
I find the new edition had changed the code in ffmpeg/ffmpeg.go.
"ffprobe := strings.Replace(strings.Split(outProbe.String(), "\n")[0], utils.LineSeparator(), "", -1)"
this change make my item appear an error.
the ffprope become "E:\ffmpeg\bin\ffprope.exe\r".

**Comment by Place1** [comment]
hey, you can work around it by doing the following for now:

```
	trans := new(transcoder.Transcoder)
	conf, _ := ffmpeg.Configure()
	conf.FfprobeBin = strings.Trim(conf.FfprobeBin, "\r")
	trans.SetConfiguration(conf)
```

**Comment by mattcanty** [comment]
This is still an issue. The workaround isn't working for me. Tried `\\r` as well but that doesn't work. Going to try specifying the executable directly.
