### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [xfrr/goffmpeg#72]
I found that this project already [supports Go modules](https://github.com/xfrr/goffmpeg/blob/master/go.mod). But sadly, the [tags](https://github.com/xfrr/goffmpeg/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/xfrr/goffmpeg v0.0.0-20200730134436-d910add31983
```
Else the mod file shows something like `github.com/xfrr/goffmpeg v0.0.0-20200730134436-d910add31983` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@xfrr @Tecuane  Could you help me review this issue? Thx :p

**Comment by Tecuane** [comment]
I'm unsure I'm the appropriate person to ask - I only submitted a single PR to fix a missing feature. I don't actually work on goffmpeg.

That said, I do agree with the use of semantic versioning if possible.

**Comment by KateGo520** [comment]
@Tecuane  Thank you for your reply!
@xfrr Could you help me review this issue? :D
