### ISSUE TITLE
How to set up multiple input

### ISSUE THREAD

**Issue by wanyhamo** [xfrr/goffmpeg#73]
SetInputPath only one input can be set,how to set up multiple input?

**Comment by wargebitebane** [comment]
You can use **SetOutputFormat**("concat") and give to ffmpeg text file as input
Text file example (tested on windows):

> file 'C:\somefolder\somefile1.mp4'
> file 'C:\somefolder\somefile2.mp4'
> file 'C:\somefolder\somefile3.mp4'

But for concat you need execute ffmpeg with "-safe 0" option and this library does not implement it yet. So you need to add a PR.

Hope it helps you
