### ISSUE TITLE
I have the ffmpeg command I don't know how it can be executed using your package

### ISSUE THREAD

**Issue by LazarenkoA** [xfrr/goffmpeg#80]
here is such a command:
`ffmpeg -filter_complex ddagrab=output_idx=1:framerate=5,hwdownload,format=bgra -c:v libx264 -crf 18 output.mp4`

**Comment by sundowndev** [comment]
Hi @LazarenkoA, you can use `SetVideoFilter`, `SetCRF` and `SetVideoCodec` methods to set those options. Look at [examples](https://github.com/xfrr/goffmpeg/blob/master/examples/hls/main.go) and [docs](https://pkg.go.dev/github.com/xfrr/goffmpeg@v1.0.0/media#File).
